export const helpContent = {
  "button-help": "<div class=\"paragraph\">\n<p>Click the <strong>Button</strong> to perform an action.\nIt&#8217;s that simple, baby.</p>\n</div>",
  "field-help": "<div class=\"paragraph\">\n<p>Enter text in the <strong>Field</strong> to provide input.\nPress <strong>Enter</strong> to submit.</p>\n</div>",
  "redirects": "<div id=\"preamble\">\n<div class=\"sectionbody\">\n<div class=\"paragraph\">\n<p>You can view redirects that you have created or add them directly yourself from the Cockpit. You must publish any changes you make to redirects.\nUse the <strong>Add</strong> button to create a new redirect, <strong>Upload</strong> to import redirects from a file, and <strong>Publish</strong> to apply changes.</p>\n</div>\n<div class=\"paragraph\">\n<p>See <a href=\"https://docs.magnolia-cms.com/paas/cockpit/sections/networking/#_create_redirects\" target=\"_blank\" rel=\"noopener\">Docs: Redirects guide</a> for more details.</p>\n</div>\n</div>\n</div>\n<div class=\"sect1\">\n<h2 id=\"_good_to_knows\">Good to knows</h2>\n<div class=\"sectionbody\">\n<div class=\"ulist\">\n<ul>\n<li>\n<p>The redirects server is a proxy server.</p>\n</li>\n<li>\n<p>Redirects are evaluated in order of appearance when entered. The first match is accepted.</p>\n</li>\n<li>\n<p>We use the Source URL to detect duplicate entries when you add a single redirect or batch import redirects (CSV).</p>\n</li>\n</ul>\n</div>\n</div>\n</div>",
  "tabs-help": "<div class=\"paragraph\">\n<p>Switch between <strong>Tabs</strong> to view different sections.\nClick a tab to activate it.</p>\n</div>",
  "redirects-deep-dive": {
    "source": "<div class=\"sect1\">\n<h2 id=\"_source\">Source</h2>\n<div class=\"sectionbody\">\n<div class=\"paragraph\">\n<p>The <strong>Source</strong> column shows the original URL that users visit. This is where the redirect begins.</p>\n</div>\n</div>\n</div>",
    "target": "<div class=\"sect1\">\n<h2 id=\"_target\">Target</h2>\n<div class=\"sectionbody\">\n<div class=\"paragraph\">\n<p>The <strong>Target</strong> column lists the new URL where users are sent. This is the destination of the redirect.</p>\n</div>\n</div>\n</div>",
    "code": "<div class=\"sect1\">\n<h2 id=\"_code\">Code</h2>\n<div class=\"sectionbody\">\n<div class=\"paragraph\">\n<p>The <strong>Code</strong> column indicates the HTTP status code (e.g., 301 for permanent, 302 for temporary). It tells browsers how to handle the redirect.</p>\n</div>\n</div>\n</div>",
    "status": "<div class=\"sect1\">\n<h2 id=\"_status\">Status</h2>\n<div class=\"sectionbody\">\n<div class=\"paragraph\">\n<p>The <strong>Status</strong> column shows if the redirect is <strong>Active</strong> or <strong>Inactive</strong>. Only active redirects are applied.</p>\n</div>\n</div>\n</div>",
    "created": "<div class=\"sect1\">\n<h2 id=\"_created\">Created</h2>\n<div class=\"sectionbody\">\n<div class=\"paragraph\">\n<p>The <strong>Created</strong> column records when the redirect was first added. Useful for tracking history!</p>\n</div>\n</div>\n</div>",
    "updated": "<div class=\"sect1\">\n<h2 id=\"_updated\">Updated</h2>\n<div class=\"sectionbody\">\n<div class=\"paragraph\">\n<p>The <strong>Updated</strong> column shows the last time the redirect was modified. Keeps you up-to-date!</p>\n</div>\n</div>\n</div>"
  }
};